project:
  name: "example-project"
  author: "17robots"
  description: "An example dyn project"
  version: "0.1.0"
  homepage: "google.com"
  license: "MIT"
  start: "src/main.dyn"
  buildOptions:
    type: lib # this tells the compiler that the package here needs to be loaded differently and incorporated sepatrately when building the project
    
# here there dont need to be any scripts unless the lib requires something to be prebuilt, but if these are there, they can be run with the scripts in the main build.yml if specified there as well, can also be specified with a --proj in the main build.yml too
scripts:
  - build: ""
  - start: ""
  - dev: ""
