import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {execute,processVideo} from '../compiler/vendor/ffmpeg/browser/pipeline.mjs';
const require=createRequire(import.meta.url);
const createCore=require(fs.realpathSync('build/browser-ffmpeg/ffmpeg-core.js'));
globalThis.self = {location:{href:'http://localhost/ffmpeg-core.js'}};
const core=await createCore({wasmBinary:fs.readFileSync('build/browser-ffmpeg/ffmpeg-core.wasm')});
core.setLogger(()=>{});
const {instance}=await WebAssembly.instantiate(fs.readFileSync(process.argv[2]));
instance.exports.dyn_initialize();
execute(core,['-f','lavfi','-i','color=c=red:s=160x90:r=8','-frames:v','8','-c:v','libvpx','-deadline','realtime','source.webm']);
const input=core.FS.readFile('source.webm').slice();
if(process.env.DYN_BROWSER_SAMPLE) fs.writeFileSync(process.env.DYN_BROWSER_SAMPLE,input);core.FS.unlink('source.webm');
for(let i=0;i<2;i++){
 const output=processVideo(core,instance.exports,input);
 assert.ok(output.length>100);
 core.FS.writeFile('verify.webm',output);
 execute(core,['-i','verify.webm','-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','verify.rgb']);
 const pixels=core.FS.readFile('verify.rgb');assert.equal(pixels.length,160*90*3);
 assert.ok(pixels[0]>30 && pixels[0]<150);assert.ok(Math.abs(pixels[0]-pixels[1])<=2);assert.ok(Math.abs(pixels[1]-pixels[2])<=2);
 core.FS.unlink('verify.webm');core.FS.unlink('verify.rgb');
}
let releasedPoisoned = false;
assert.throws(()=>processVideo(core,{allocate(){throw new WebAssembly.RuntimeError('trap')},release(){releasedPoisoned=true}},input),WebAssembly.RuntimeError);
assert.equal(releasedPoisoned,false);
assert.throws(()=>processVideo(core,instance.exports,new Uint8Array([1,2,3])),/FFmpeg failed/);
assert.ok(processVideo(core,instance.exports,input).length>100);
for(const name of ['input.bin','decoded.rgba','edited.rgba','output.webm']) assert.equal(core.FS.analyzePath(name).exists,false);
console.log('PASS real FFmpeg Wasm decode -> Dyn arena/filter -> FFmpeg encode; repeated jobs, malformed input, cleanup');
