use std::fmt::Display;

#[derive(Clone, Debug)]
pub enum Token {
    Eof,

    // operators
    LParen,
    RParen,
    LBrack,
    RBrack,
    LBrace,
    RBrace,
    Comma,
    Semicolon,
    Colon,
    Dot,
    DotDot,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    ModAssign,
    AndAssign,
    OrAssign,
    XorAssign,
    Add,
    AddAdd,
    Sub,
    SubSub,
    Mul,
    Div,
    Mod,
    And,
    AndAnd,
    Or,
    OrOr,
    Xor,
    Lesser,
    LesserEqual,
    RightShift,
    Greater,
    GreaterEqual,
    LeftShift,
    Equal,
    EqualEqual,
    Bang,
    BangEqual,

    // keywords
    Mut,
    If,
    For,
    Con,
    Match,
    True,
    False,
    Break,
    Continue,
    Defer,
    Enum,
    Struct,
    Pub,
    Void,
    Return,

    // literals
    Ident(String),
    Int(u128),
    Float(f64),
    String(String),
}

impl Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::Eof => write!(f, ""),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::LBrack => write!(f, "["),
            Token::RBrack => write!(f, "]"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::Colon => write!(f, ":"),
            Token::Dot => write!(f, "."),
            Token::DotDot => write!(f, ".."),
            Token::AddAssign => write!(f, "+="),
            Token::SubAssign => write!(f, "-="),
            Token::MulAssign => write!(f, "*="),
            Token::DivAssign => write!(f, "/="),
            Token::ModAssign => write!(f, "%="),
            Token::AndAssign => write!(f, "&="),
            Token::OrAssign => write!(f, "|="),
            Token::XorAssign => write!(f, "^="),
            Token::Add => write!(f, "+"),
            Token::AddAdd => write!(f, "++"),
            Token::Sub => write!(f, "-"),
            Token::SubSub => write!(f, "--"),
            Token::Mul => write!(f, "*"),
            Token::Div => write!(f, "/"),
            Token::Mod => write!(f, "%"),
            Token::And => write!(f, "&"),
            Token::AndAnd => write!(f, "&&"),
            Token::Or => write!(f, "|"),
            Token::OrOr => write!(f, "||"),
            Token::Xor => write!(f, "^"),
            Token::Lesser => write!(f, "<"),
            Token::LesserEqual => write!(f, "<="),
            Token::RightShift => write!(f, ">>"),
            Token::Greater => write!(f, ">"),
            Token::GreaterEqual => write!(f, ">="),
            Token::LeftShift => write!(f, "<<"),
            Token::Equal => write!(f, "="),
            Token::EqualEqual => write!(f, "=="),
            Token::Bang => write!(f, "!"),
            Token::BangEqual => write!(f, "!="),
            Token::Mut => write!(f, "mut"),
            Token::If => write!(f, "if"),
            Token::For => write!(f, "for"),
            Token::Con => write!(f, "con"),
            Token::Match => write!(f, "match"),
            Token::True => write!(f, "true"),
            Token::False => write!(f, "false"),
            Token::Break => write!(f, "break"),
            Token::Continue => write!(f, "continue"),
            Token::Defer => write!(f, "defer"),
            Token::Enum => write!(f, "enum"),
            Token::Struct => write!(f, "struct"),
            Token::Pub => write!(f, "pub"),
            Token::Void => write!(f, "void"),
            Token::Return => write!(f, "return"),
            Token::Ident(s) => write!(f, "ident: {}", s),
            Token::Int(s) => write!(f, "int: {}", s),
            Token::Float(s) => write!(f, "float: {}", s),
            Token::String(s) => write!(f, "string: {}", s),
        }
    }
}
