#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum RuntimeReturnKind {
    U32,
    U64,
    I64,
    I32,
    BytesSlice,
    IdentityI32Fn,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum RuntimeAbiType {
    Ptr,
    I32,
    I64,
    F64,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct RuntimeIntrinsicSpec {
    pub builtin: &'static str,
    pub symbol: &'static str,
    pub arity: usize,
    pub return_kind: RuntimeReturnKind,
    pub abi_params: &'static [RuntimeAbiType],
    pub abi_return: RuntimeAbiType,
}

pub const RUNTIME_INTRINSICS: &[RuntimeIntrinsicSpec] = &[
    RuntimeIntrinsicSpec {
        builtin: "$alloc",
        symbol: "dynrt_alloc",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$realloc",
        symbol: "dynrt_realloc",
        arity: 4,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$free",
        symbol: "dynrt_free",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$c_allocator",
        symbol: "dynrt_c_allocator",
        arity: 0,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$test_failing_allocator",
        symbol: "dynrt_test_failing_allocator",
        arity: 0,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$test_set_fail_after",
        symbol: "dynrt_test_set_fail_after",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$test_identity_i32_fn",
        symbol: "dynrt_test_identity_i32_fn",
        arity: 0,
        return_kind: RuntimeReturnKind::IdentityI32Fn,
        abi_params: &[],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$arena_allocator",
        symbol: "dynrt_arena_allocator",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$arena_reset",
        symbol: "dynrt_arena_reset",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$arena_deinit",
        symbol: "dynrt_arena_deinit",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$alloc_with",
        symbol: "dynrt_alloc_with",
        arity: 3,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$realloc_with",
        symbol: "dynrt_realloc_with",
        arity: 5,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$free_with",
        symbol: "dynrt_free_with",
        arity: 4,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$mem_copy",
        symbol: "dynrt_mem_copy",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$mem_move",
        symbol: "dynrt_mem_move",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$mem_set",
        symbol: "dynrt_mem_set",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::I32,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$mem_eq",
        symbol: "dynrt_mem_eq",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_init",
        symbol: "dynrt_vec_i32_init",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_deinit",
        symbol: "dynrt_vec_i32_deinit",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_len",
        symbol: "dynrt_vec_i32_len",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_cap",
        symbol: "dynrt_vec_i32_cap",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_push",
        symbol: "dynrt_vec_i32_push",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::I32],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_get",
        symbol: "dynrt_vec_i32_get",
        arity: 2,
        return_kind: RuntimeReturnKind::I32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_set",
        symbol: "dynrt_vec_i32_set",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::I32,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_pop",
        symbol: "dynrt_vec_i32_pop",
        arity: 1,
        return_kind: RuntimeReturnKind::I32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_clear",
        symbol: "dynrt_vec_i32_clear",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_i32_reserve",
        symbol: "dynrt_vec_i32_reserve",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_init",
        symbol: "dynrt_vec_raw_init",
        arity: 3,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_deinit",
        symbol: "dynrt_vec_raw_deinit",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_len",
        symbol: "dynrt_vec_raw_len",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_cap",
        symbol: "dynrt_vec_raw_cap",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_push_u64",
        symbol: "dynrt_vec_raw_push_u64",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::I64],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_get_u64",
        symbol: "dynrt_vec_raw_get_u64",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I64,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_set_u64",
        symbol: "dynrt_vec_raw_set_u64",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::I64,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_pop_u64",
        symbol: "dynrt_vec_raw_pop_u64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I64,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_clear",
        symbol: "dynrt_vec_raw_clear",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_reserve",
        symbol: "dynrt_vec_raw_reserve",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_ptr",
        symbol: "dynrt_vec_raw_ptr",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_push_bytes",
        symbol: "dynrt_vec_raw_push_bytes",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_get_bytes",
        symbol: "dynrt_vec_raw_get_bytes",
        arity: 4,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_set_bytes",
        symbol: "dynrt_vec_raw_set_bytes",
        arity: 4,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$vec_raw_pop_bytes",
        symbol: "dynrt_vec_raw_pop_bytes",
        arity: 3,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$io_write_i32",
        symbol: "dynrt_io_write_i32",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::I32, RuntimeAbiType::I32],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$io_write",
        symbol: "dynrt_io_write",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::I32,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_len",
        symbol: "dynrt_bytes_len",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_from_ptr_len",
        symbol: "dynrt_bytes_from_ptr_len",
        arity: 2,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_eq",
        symbol: "dynrt_bytes_eq",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_starts_with",
        symbol: "dynrt_bytes_starts_with",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_ends_with",
        symbol: "dynrt_bytes_ends_with",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_index_of",
        symbol: "dynrt_bytes_index_of",
        arity: 2,
        return_kind: RuntimeReturnKind::I64,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_clone",
        symbol: "dynrt_bytes_clone",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_slice",
        symbol: "dynrt_bytes_slice",
        arity: 3,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_concat2",
        symbol: "dynrt_bytes_concat2",
        arity: 2,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$bytes_concat3",
        symbol: "dynrt_bytes_concat3",
        arity: 3,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fmt_i32",
        symbol: "dynrt_fmt_i32",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[RuntimeAbiType::I32, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fmt_u64",
        symbol: "dynrt_fmt_u64",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[RuntimeAbiType::I64, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fmt_usize",
        symbol: "dynrt_fmt_usize",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$env_argc",
        symbol: "dynrt_env_argc",
        arity: 0,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$env_argv",
        symbol: "dynrt_env_argv",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$env_get",
        symbol: "dynrt_env_get",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$env_cwd",
        symbol: "dynrt_env_cwd",
        arity: 0,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_exists",
        symbol: "dynrt_fs_exists",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_is_dir",
        symbol: "dynrt_fs_is_dir",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_read_all",
        symbol: "dynrt_fs_read_all",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_write_all",
        symbol: "dynrt_fs_write_all",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_mkdir_all",
        symbol: "dynrt_fs_mkdir_all",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$fs_list_dir",
        symbol: "dynrt_fs_list_dir",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_join",
        symbol: "dynrt_path_join",
        arity: 2,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_normalize",
        symbol: "dynrt_path_normalize",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_dirname",
        symbol: "dynrt_path_dirname",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_basename",
        symbol: "dynrt_path_basename",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_extension",
        symbol: "dynrt_path_extension",
        arity: 1,
        return_kind: RuntimeReturnKind::BytesSlice,
        abi_params: &[
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
            RuntimeAbiType::Ptr,
        ],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$path_is_abs",
        symbol: "dynrt_path_is_abs",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_zero",
        symbol: "dynrt_f128_zero",
        arity: 0,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_from_literal",
        symbol: "dynrt_f128_from_literal",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_from_f64",
        symbol: "dynrt_f128_from_f64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::F64],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_from_i64",
        symbol: "dynrt_f128_from_i64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::I64],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_from_u64",
        symbol: "dynrt_f128_from_u64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::I64],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_to_f64",
        symbol: "dynrt_f128_to_f64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::F64,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_to_i64",
        symbol: "dynrt_f128_to_i64",
        arity: 1,
        return_kind: RuntimeReturnKind::I64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I64,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_to_u64",
        symbol: "dynrt_f128_to_u64",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I64,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_neg",
        symbol: "dynrt_f128_neg",
        arity: 1,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_add",
        symbol: "dynrt_f128_add",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_sub",
        symbol: "dynrt_f128_sub",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_mul",
        symbol: "dynrt_f128_mul",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_div",
        symbol: "dynrt_f128_div",
        arity: 2,
        return_kind: RuntimeReturnKind::U64,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::Ptr,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_eq",
        symbol: "dynrt_f128_eq",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_ne",
        symbol: "dynrt_f128_ne",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_lt",
        symbol: "dynrt_f128_lt",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_le",
        symbol: "dynrt_f128_le",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_gt",
        symbol: "dynrt_f128_gt",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_ge",
        symbol: "dynrt_f128_ge",
        arity: 2,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr, RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
    RuntimeIntrinsicSpec {
        builtin: "$f128_release",
        symbol: "dynrt_f128_release",
        arity: 1,
        return_kind: RuntimeReturnKind::U32,
        abi_params: &[RuntimeAbiType::Ptr],
        abi_return: RuntimeAbiType::I32,
    },
];

pub fn runtime_intrinsic_for_builtin(name: &str) -> Option<&'static RuntimeIntrinsicSpec> {
    RUNTIME_INTRINSICS
        .iter()
        .find(|intrinsic| intrinsic.builtin == name)
}

pub fn runtime_intrinsic_for_symbol(symbol: &str) -> Option<&'static RuntimeIntrinsicSpec> {
    RUNTIME_INTRINSICS
        .iter()
        .find(|intrinsic| intrinsic.symbol == symbol)
}

pub fn runtime_symbol_for_builtin(name: &str) -> Option<&'static str> {
    runtime_intrinsic_for_builtin(name).map(|intrinsic| intrinsic.symbol)
}

pub fn runtime_arity_for_builtin(name: &str) -> Option<usize> {
    runtime_intrinsic_for_builtin(name).map(|intrinsic| intrinsic.arity)
}

pub fn runtime_arity_for_symbol(symbol: &str) -> Option<usize> {
    runtime_intrinsic_for_symbol(symbol).map(|intrinsic| intrinsic.arity)
}

pub fn runtime_return_kind_for_builtin(name: &str) -> Option<RuntimeReturnKind> {
    runtime_intrinsic_for_builtin(name).map(|intrinsic| intrinsic.return_kind)
}

pub fn runtime_return_kind_for_symbol(symbol: &str) -> Option<RuntimeReturnKind> {
    runtime_intrinsic_for_symbol(symbol).map(|intrinsic| intrinsic.return_kind)
}

pub fn runtime_abi_for_symbol(symbol: &str) -> Option<(&'static [RuntimeAbiType], RuntimeAbiType)> {
    runtime_intrinsic_for_symbol(symbol)
        .map(|intrinsic| (intrinsic.abi_params, intrinsic.abi_return))
}

#[cfg(test)]
mod tests;
