version: 3.2
services:
  pub:
    build:
      context: .
      dockerfile: ./docker/publisher/Dockerfile
    networks:
      - net
  sub:
    build:
      context: .
      dockerfile: ./docker/subscriber/Dockerfile
    networks:
      - net
  rabbit:
    image: rabbit:management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
networks:
  net:
    driver: bridge
