#!/usr/bin/env python3
"""Generate SDK reference pages using the compiler's declaration parser."""
import argparse, json, os, re, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--check', action='store_true')
p.add_argument('--dyn', default=os.environ.get('DYN', str(ROOT/'build/dyn-release')))
a = p.parse_args()
# Only behavioral assertions reviewed in these fixtures are classified here.
contracts = {
 'std/container/slot_map': ('Borrows disjoint record, generation and occupancy backing. Handles include backing identity; initialize generation storage to zero once and preserve it thereafter. Views expire on removal/reinitialization. copy_into can retain bytes in disjoint caller storage.', 'Invalid/stale/foreign handles return missing; copy_into reports Missing or Capacity without writing. Saturated generations retire slots. Not a security capability or a lifetime proof.'),
 'std/mem': ('Arena owns heap backing or borrows caller storage. Reset/rewind/release invalidate affected allocations; pools and free lists recycle slots within backing storage. Buffer-backed arenas never fall back to the heap.', 'Try APIs report capacity/alignment/overflow/state/system failures. Failed arena allocation preserves the cursor; checked APIs may panic.'),
 'std/encoding/json': ('DOM nodes borrow their arena; constructed text and keys borrow caller slices. Each node has at most one parent. Public linkage fields are read-only to callers. There is no implicit detach or clone.', 'Invalid attachment, cycles and reparenting return false without mutating links or keys. Capacity failure returns nil/failed result. Check the specific parser result before retaining nodes.'),
 'std/io': ('Reader/Writer retain their context pointers; caller keeps those contexts and buffers alive. Copy scratch is caller-owned and may live on the stack.', 'Copy results report partial progress and provider errors. Empty scratch is rejected before consuming input; copy_n stops at its bound or EOF. Read/write calls may complete partially.'),
 'std/strings': ('View helpers borrow source. clone/join copy into destination or arena storage. split allocates only its table and still borrows source bytes for every element; keep both alive. An arena parameter does not imply a deep copy.', 'Inspect boolean/result fields for parsing and capacity failures. ASCII helpers operate on ASCII bytes; they do not implement Unicode case folding.'),
}
behavior = json.loads((ROOT/'docs/release/sdk-behavior.json').read_text())
for contract in behavior['contracts']:
    for fixture in contract['fixtures']:
        assert (ROOT/fixture).is_file(), f'missing behavior fixture: {fixture}'
references = json.loads((ROOT/'docs/release/sdk-api-references.json').read_text())
by_package = {}
for entry in references['declarations']:
    by_package.setdefault(entry['package'], []).append(entry)
outputs = {}
index = ['# SDK reference', '', 'Generated by `tools/sdk-reference.py` using `dyn docs`; edit source comments and generator metadata, then regenerate.', '',
         'Signatures include every source file, including target-gated alternatives. A listed declaration is not a promise of availability on every target. Source comments remain the API contract; missing prose is explicitly unreviewed.', '',
         'Examples link to executable fixtures. Mechanical references are navigation aids, not proof of behavioral coverage. Native providers retain their own allocation/lifetime contracts; Dyn-owned heap allocation goes through `std/mem` arenas.', '',
         '| Package | Public declarations | Direct fixture references |', '| --- | ---: | ---: |']
for package, entries in sorted(by_package.items()):
    filename = package.replace('/', '-') + '.md'
    docs = subprocess.run([a.dyn, 'docs', 'compiler/'+package], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    docs = docs.split('\n', 1)[1].lstrip().replace('](compiler/', '](../../compiler/')
    tests = sorted({t for entry in entries for t in entry['direct_test_references']})
    storage, failure = contracts.get(package, (
        'Storage and retention details are declaration-specific; read the adjacent source contracts. Arena parameters allocate from the supplied arena; slices/pointers do not transfer ownership by themselves.',
        'Failure and rollback details require declaration-level review. Do not infer atomicity, partial-progress behavior, or panic behavior from the function name.'))
    reviewed = sorted({t for contract in behavior['contracts'] if package in contract['packages'] for t in contract['fixtures']})
    lines = ['# '+package, '', '[Reference index](README.md)', '', '## Storage and lifetime', '', storage, '', '## Failure behavior', '', failure, '',
             '## Platforms', '', 'Target gates are shown with each source below. Ungated code may still call a target-gated dependency. See [support policy](../stability.md) and native-provider requirements in source `#link` directives.', '',
             '## Examples and tests', '']
    if tests:
        lines += [f'- [{t}](../../{t})' for t in tests]
    else: lines += ['No direct checked-in Dyn fixture reference found; generated/transitive tests may exist. This is a review gap, not a declaration of coverage.']
    lines += ['', 'Reviewed behavioral fixtures: '+(', '.join(f'[{t}](../../{t})' for t in reviewed) if reviewed else 'no package-wide behavioral claim; inspect linked assertions.'), '', '## Declarations and source contracts', '', docs]
    outputs[filename] = '\n'.join(lines).rstrip()+'\n'
    index += [f'| [{package}]({filename}) | {len(entries)} | {len(tests)} |']
outputs['README.md'] = '\n'.join(index)+'\n'
destination = ROOT/'docs/reference'
destination.mkdir(exist_ok=True)
for name, text in outputs.items():
    path = destination/name
    if a.check:
        assert path.exists() and path.read_text()==text, f'stale SDK reference: {path}; run tools/sdk-reference.py'
    else: path.write_text(text)
extra = set(p.name for p in destination.glob('*.md'))-set(outputs)
assert not extra, f'remove obsolete generated reference pages: {sorted(extra)}'
print(f'SDK reference: {len(by_package)} packages, {len(references["declarations"])} declarations; signatures, contracts, target gates and fixture links')
