project:
  name: "example-project"
  author: "17robots"
  description: "An example dyn project"
  version: "0.1.0"
  homepage: "google.com"
  license: "MIT"
  start: "src/main.dyn"
  buildOptions:
    type: console
workspace:
  - otherpkg:
    src: "../otherpkg"
    options:
    cache: false
    version: "0.0.1"
    type: lib
  - helper:
    src: "../otherpkg"
    cache: true
    version: "0.1.0"
    type: lib
dependencies:
  - "md5@latest"
  - http:
    - verison: latest
    - cache: false
scripts:
  - build: ""
  - start: ""
  - dev: ""

