const std = @import("std");
const Token = @import("token.zig").TokenType;

pub const LiteralKind = enum {
    string,
    int,
    float,
    boolean,
    char,
    null,
    undefined,
    pub fn to_string(s: LiteralKind) []const u8 {
        return switch (s) {
            .string => "string",
            .int => "int",
            .float => "float",
            .boolean => "boolean",
            .char => "char",
            .null => "null",
            .undefined => "undefined",
        };
    }
};

pub const AssignOp = enum {
    addeq,
    subeq,
    muleq,
    diveq,
    modeq,
    xoreq,
    andeq,
    oreq,
    eq,
    pub fn to_string(s: AssignOp) []const u8 {
        return switch (s) {
            .addeq => "addeq",
            .subeq => "subeq",
            .muleq => "muleq",
            .diveq => "diveq",
            .modeq => "modeq",
            .xoreq => "xoreq",
            .andeq => "andeq",
            .oreq => "oreq",
            .eq => "eq",
        };
    }
};

pub const Op = enum {
    add,
    sub,
    mul,
    div,
    mod,
    xor,
    @"and",
    @"or",
    eqeq,
    gt,
    gte,
    lt,
    lte,
    bang,
    andand,
    oror,
    bangeq,
    nullish,
    pub fn to_string(s: Op) []const u8 {
        return switch (s) {
            .add => "add",
            .sub => "sub",
            .mul => "mul",
            .div => "div",
            .mod => "mod",
            .xor => "xor",
            .@"and" => "and",
            .@"or" => "or",
            .eqeq => "eqeq",
            .bang => "bang",
            .gt => "gt",
            .gte => "gte",
            .lt => "lt",
            .lte => "lte",
            .andand => "andand",
            .oror => "oror",
            .bangeq => "bangeq",
            .nullish => "nullish",
        };
    }
};

pub const Node = union(enum) {
    program: struct { declarations: std.ArrayList(Node) },
    module: struct { name: *Node },
    identifier: struct { value: []const u8 },
    declaration: struct { pub_: bool, name: *Node, type: ?*Node, val: *Node },
    mut_declaration: struct { mut: bool, name: *Node, type: ?*Node, val: ?*Node },
    block: struct { label: ?*Node, statements: std.ArrayList(Node) },
    arrow_expression: struct { expression: *Node },
    assign_expression: struct { left: *Node, op: AssignOp, right: *Node },
    if_prefix: struct { expression: *Node, capture: ?*Node },
    for_prefix: struct { expressions: std.ArrayList(Node), capture: *Node },
    while_prefix: struct { expression: *Node, capture: ?*Node },
    match: struct { expression: *Node, arms: std.ArrayList(Node) },
    arm: struct { expressions: std.ArrayList(Node), capture: ?*Node, result: *Node },
    if_statement: struct { prefix: *Node, body: *Node, else_body: ?*Node },
    for_statement: struct { inline_: bool, prefix: *Node, body: *Node },
    while_statement: struct { prefix: *Node, body: *Node },
    defer_statement: struct { capture: ?*Node, body: *Node },
    capture_val: struct { mut: bool, val: *Node },
    capture: struct { captures: std.ArrayList(Node) },
    return_expression: struct { val: ?*Node },
    break_expression: struct { label: ?*Node, val: ?*Node },
    continue_expression: struct { label: ?*Node },
    nullish_expression: struct { a: *Node, b: *Node },
    range_expression: struct { a: *Node, b: *Node },
    array_init: struct { vals: std.ArrayList(Node) },
    struct_init: struct { name: ?*Node, inits: std.ArrayList(Node) },
    struct_init_member: struct { name: *Node, val: *Node },
    enum_error_init: struct { name: *Node, val: ?*Node },
    struct_: struct { members: std.ArrayList(Node) },
    struct_member: struct { names: std.ArrayList(Node), type: *Node, val: ?*Node },
    enum_: struct { members: std.ArrayList(Node) },
    enum_member: struct { name: *Node, type: ?*Node },
    error_: struct { members: std.ArrayList(Node) },
    error_member: struct { name: *Node, type: ?*Node },
    if_expression: struct { prefix: *Node, body: *Node, else_body: ?*Node },
    for_expression: struct { prefix: *Node, body: *Node },
    while_expression: struct { prefix: *Node, body: *Node },
    optional_type: struct { expression: *Node },
    pointer_type: struct { expression: *Node },
    optional_dereference: struct { expression: *Node },
    pointer_dereference: struct { expression: *Node },
    comp_expression: struct { expression: *Node },
    call: struct { name: *Node, args: std.ArrayList(Node) },
    try_: struct { expression: *Node },
    catch_: struct { capture: ?*Node, expression: *Node, body: *Node },
    member_access: struct { name: *Node, member: *Node },
    array_index: struct { name: *Node, index: *Node },
    array_type: struct { expression: *Node },
    error_union_type: struct { name: ?*Node, errors: std.ArrayList(Node) },
    grouped: struct { expression: ?*Node },
    use: struct { path: *Node },
    literal: struct { kind: LiteralKind, val: []const u8 },
    unary: struct { op: Op, b: *Node },
    binary: struct { a: *Node, op: Op, b: *Node },
    function: struct { inline_: bool, parameters: std.ArrayList(Node), result: ?*Node, body: *Node },
    function_parameter: struct { names: std.ArrayList(Node), type: *Node },
    function_type: struct { parameters: std.ArrayList(Node), result: ?*Node },
    underscore,
    @"type",
};
