const std = @import("std");
const Span = @import("token.zig").Span;

pub const LiteralKind = enum {
    string,
    int,
    float,
    boolean,
    char,
    null,
    undefined,
    pub fn to_string(s: LiteralKind) []const u8 {
        return switch (s) {
            .string => "string",
            .int => "int",
            .float => "float",
            .boolean => "boolean",
            .char => "char",
            .null => "null",
            .undefined => "undefined",
        };
    }
};

pub const Node = union(enum) {
    add: struct { span: Span },
    addeq: struct { span: Span },
    @"and": struct { span: Span },
    andand: struct { span: Span },
    andeq: struct { span: Span },
    arm: struct { expressions: std.ArrayList(Node), capture: ?*Node, result: *Node, span: Span },
    array_index: struct { name: *Node, index: *Node, span: Span },
    array_init: struct { vals: std.ArrayList(Node), span: Span },
    array_type: struct { expression: *Node, span: Span },
    arrow_expression: struct { expression: *Node, span: Span },
    assign_expression: struct { left: *Node, op: *Node, right: *Node, span: Span },
    bang: struct { span: Span },
    bangeq: struct { span: Span },
    binary: struct { a: *Node, op: *Node, b: *Node, span: Span },
    block: struct { label: ?*Node, statements: std.ArrayList(Node), span: Span },
    break_expression: struct { label: ?*Node, val: ?*Node, span: Span },
    call: struct { name: *Node, args: std.ArrayList(Node), span: Span },
    capture: struct { captures: std.ArrayList(Node), span: Span },
    capture_val: struct { mut: bool, val: *Node, span: Span },
    catch_: struct { capture: ?*Node, expression: *Node, body: *Node, span: Span },
    comp_expression: struct { expression: *Node, span: Span },
    continue_expression: struct { label: ?*Node, span: Span },
    declaration: struct { pub_: bool, mut: bool, name: *Node, type: ?*Node, val: ?*Node, span: Span },
    defer_statement: struct { capture: ?*Node, body: *Node, span: Span },
    div: struct { span: Span },
    diveq: struct { span: Span },
    enum_: struct { members: std.ArrayList(Node), span: Span },
    enum_error_init: struct { name: *Node, val: ?*Node, span: Span },
    eq: struct { span: Span },
    eqeq: struct { span: Span },
    error_: struct { members: std.ArrayList(Node), span: Span },
    error_union_type: struct { name: ?*Node, errors: std.ArrayList(Node), span: Span },
    for_statement: struct { inline_: bool, expressions: std.ArrayList(Node), capture: *Node, body: *Node, span: Span },
    function: struct { inline_: bool, parameters: std.ArrayList(Node), result: ?*Node, body: *Node, span: Span },
    function_parameter: struct { names: std.ArrayList(Node), type: *Node, span: Span },
    function_type: struct { parameters: std.ArrayList(Node), result: ?*Node, span: Span },
    grouped: struct { expression: ?*Node, span: Span },
    gt: struct { span: Span },
    gte: struct { span: Span },
    identifier: struct { name: []const u8, span: Span },
    if_prefix: struct { expression: *Node, capture: ?*Node, span: Span },
    if_statement: struct { prefix: *Node, body: *Node, else_body: ?*Node, span: Span },
    if_expression: struct { prefix: *Node, body: *Node, else_body: *Node, span: Span },
    literal: struct { kind: LiteralKind, val: []const u8, span: Span },
    lt: struct { span: Span },
    lte: struct { span: Span },
    match: struct { expression: *Node, arms: std.ArrayList(Node), span: Span },
    member: struct { names: std.ArrayList(Node), type: ?*Node, val: ?*Node, span: Span },
    member_access: struct { name: *Node, member: *Node, span: Span },
    mod: struct { span: Span },
    modeq: struct { span: Span },
    module: struct { name: *Node, span: Span },
    mul: struct { span: Span },
    muleq: struct { span: Span },
    nullish: struct { span: Span },
    nullish_expression: struct { a: *Node, b: *Node, span: Span },
    optional_dereference: struct { expression: *Node, span: Span },
    optional_type: struct { expression: *Node, span: Span },
    @"or": struct { span: Span },
    oreq: struct { span: Span },
    oror: struct { span: Span },
    pointer_dereference: struct { expression: *Node, span: Span },
    pointer_type: struct { expression: *Node, span: Span },
    program: struct { declarations: std.ArrayList(Node), span: Span },
    range_expression: struct { a: *Node, b: *Node, span: Span },
    return_expression: struct { val: ?*Node, span: Span },
    struct_: struct { members: std.ArrayList(Node), span: Span },
    struct_init: struct { name: ?*Node, inits: std.ArrayList(Node), span: Span },
    struct_init_member: struct { name: *Node, val: *Node, span: Span },
    sub: struct { span: Span },
    subeq: struct { span: Span },
    try_: struct { expression: *Node, span: Span },
    type: struct { span: Span },
    unary: struct { op: *Node, b: *Node, span: Span },
    underscore: struct { span: Span },
    use: struct { path: *Node, span: Span },
    while_statement: struct { expression: *Node, capture: ?*Node, body: *Node, span: Span },
    xor: struct { span: Span },
    xoreq: struct { span: Span },
};
