const std = @import("std");
const Token = @import("token.zig").TokenType;

pub const LiteralKind = enum {
    string,
    int,
    float,
    boolean,
    char,
    null,
    undefined,
    pub fn to_string(s: LiteralKind) []const u8 {
        return switch (s) {
            .string => "string",
            .int => "int",
            .float => "float",
            .boolean => "boolean",
            .char => "char",
            .null => "null",
            .undefined => "undefined",
        };
    }
};
pub const Op = enum {
    add,
    addeq,
    sub,
    subeq,
    mul,
    muleq,
    div,
    diveq,
    mod,
    modeq,
    xor,
    xoreq,
    @"and",
    andeq,
    @"or",
    oreq,
    @"else",
    eqeq,
    dotdot,
    eq,
    pub fn to_string(s: Op) []const u8 {
        return switch (s) {
            .add => "add",
            .addeq => "addeq",
            .sub => "sub",
            .subeq => "subeq",
            .mul => "mul",
            .muleq => "muleq",
            .div => "div",
            .diveq => "diveq",
            .mod => "mod",
            .modeq => "modeq",
            .xor => "xor",
            .xoreq => "xoreq",
            .@"and" => "and",
            .andeq => "andeq",
            .@"or" => "or",
            .oreq => "oreq",
            .@"else" => "else",
            .eqeq => "eqeq",
            .dotdot => "dotdot",
            .eq => "eq",
        };
    }
};

pub const Node = union(enum) {
    program: struct {declarations: std.ArrayList(Node)},
    module: struct {name: *Node},
    identifier: struct {value: []const u8},
    declaration: struct { pub_: bool, name: *Node, type: ?*Node, val: *Node},
    mut_declaration: struct { mut: bool, name: *Node, type: ?*Node, val: ?*Node},
    block: struct { statements: std.ArrayList(Node) },
    arrow_expression: struct { expression: *Node },
    assign_expression: struct { left: *Node, op: anyopaque, right: *Node },
    if_prefix: struct { expression: *Node, capture: ?*Node },
    for_prefix: struct { expressions: std.ArrayList(Node), capture: *Node },
    while_prefix: struct { expression: *Node, capture: ?*Node },
    match: struct{ expression: *Node, arms: std.ArrayList(Node) },
    arm: struct { expressions: std.ArrayList(Node), capture: ?*Node, result: *Node },
    if_statement: struct { prefix: *Node, body: *Node, else_body: ?*Node },
    for_statement: struct { prefix: *Node, body: *Node },
    while_statement: struct { prefix: *Node, body: *Node },
    defer_statement: struct { capture: ?*Node, body: *Node },
    capture_val: struct { mut: bool, val: *Node },
    capture: struct { captures: std.ArrayList(Node) },
    return_expression: struct { val: ?*Node },
    break_expression: struct { label: ?*Node, val: ?*Node },
    continue_expression: struct { label: ?*Node },
    nullish_expression: struct { a: *Node, b: *Node },
    range_expression: struct { a: *Node, b: *Node },
    array_init: struct { vals: std.ArrayList(Node) },
    struct_init: struct { name: ?*Node, inits: std.ArrayList(Node) },
    struct_init_member: struct { name: *Node, val: *Node },
    enum_error_init: struct { name: *Node, val: ?*Node },
    struct_: struct { members: std.ArrayList(Node) },
    struct_member: struct { names: std.ArrayList(Node), type: *Node, val: ?*Node },
    enum_: struct { members: std.ArrayList(Node) },
    enum_member: struct { name: *Node, type: ?*Node },
    error_: struct { members: std.ArrayList(Node) },
    error_member: struct { name: *Node, type: ?*Node },
    if_expression: struct { prefix: *Node, body: *Node, else_body: ?*Node },
    for_expression: struct { prefix: *Node, body: *Node },
    while_expression: struct { prefix: *Node, body: *Node },
};
