const Span = @import("source.zig").Span;
pub const TokenKind = enum {
    eof,
    newline,
    semicolon,
    doc_comment,

    identifier,
    builtin_identifier,
    integer,
    float,
    string,
    char,
    true,
    false,
    null,

    kw_module,
    kw_packed,
    kw_type,
    kw_use,
    kw_pub,
    kw_mut,
    kw_struct,
    kw_enum,
    kw_if,
    kw_else,
    kw_match,
    kw_for,
    kw_return,
    kw_break,
    kw_continue,
    kw_defer,
    kw_comp,
    kw_inline,
    kw_or,

    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    comma,
    colon,
    dot,
    question,
    bang,
    plus,
    minus,
    star,
    slash,
    percent,
    amp,
    pipe,
    caret,
    tilde,
    dollar,
    equal,
    less,
    greater,

    colon_equal,
    equal_equal,
    bang_equal,
    less_equal,
    greater_equal,
    plus_equal,
    minus_equal,
    star_equal,
    slash_equal,
    percent_equal,
    amp_amp,
    pipe_pipe,
    shift_left,
    shift_right,
    dot_dot,
    dot_dot_equal,
    equal_greater,
    dot_question,
    dot_bang,
    dot_star,
};
pub const Token = struct { kind: TokenKind, span: Span };

pub fn keyword(bytes: []const u8) ?TokenKind {
    inline for (.{
        .{ "module", .kw_module },
        .{ "packed", .kw_packed },
        .{ "type", .kw_type },
        .{ "use", .kw_use },
        .{ "pub", .kw_pub },
        .{ "mut", .kw_mut },
        .{ "struct", .kw_struct },
        .{ "enum", .kw_enum },
        .{ "if", .kw_if },
        .{ "else", .kw_else },
        .{ "match", .kw_match },
        .{ "for", .kw_for },
        .{ "return", .kw_return },
        .{ "break", .kw_break },
        .{ "continue", .kw_continue },
        .{ "defer", .kw_defer },
        .{ "comp", .kw_comp },
        .{ "inline", .kw_inline },
        .{ "or", .kw_or },
    }) |entry| if (std.mem.eql(u8, bytes, entry[0])) return entry[1];
    return null;
}
