pub const Type = union(enum) {
    array: struct {
        len: comptime_int,
        child: Type,
    },
    comp_float: void,
    comp_int: void,
    @"enum": struct {
        fields: []const struct {
            name: []const u8,
            type: ?Type,
            alignment: ?comptime_int,
        },
        enum_declarations: []const Declaration,
    },
    err_union: struct {},
    @"error": struct {
        fields: []const struct {
            name: []const u8,
            type: ?Type,
            alignment: ?comptime_int,
        },
        error_declarations: []const Declaration,
    },
    float: struct {},
    function: struct {
        calling_convention: struct {},
        generic: bool,
        return_type: ?Type,
        params: []const struct {
            generic: bool,
            type: ?Type,
        },
    },
    int: struct { signed: bool, width: u16 },
    null: void,
    optional: struct { child: Type },
    pointer: struct {
        size: enum { one, many, slice, c },
        is_const: bool,
        is_volatile: bool,
        alignment: u16,
        address_space: enum {
            generic,
            gs,
            fs,
            ss,
            global,
            constant,
            param,
            shared,
            local,
            input,
            output,
            uniform,
            push_constant,
            storage_buffer,
            physical_storage_buffer,
            flash,
            flash1,
            flash2,
            flash3,
            flash4,
            flash5,
            cog,
            hub,
            lut,
        },
        child: Type,
        allow_zero: bool,
    },
    @"struct": struct {
        fields: []const struct {
            name: []const u8,
            type: Type,
            comp: bool,
            alignment: comptime_int,
        },
        struct_declarations: []const Declaration,
    },
    type: void,
    undefined: void,
    void: void,
    pub const Declaration = struct { name: []const u8 };
};
